# Copyright (c) 2024 Cloudflare, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

disallowed-methods = [
    { path = "std::time::Instant::now", reason = "not implemented in wasm" },
]
