# Copyright (c) 2024 Cloudflare, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
---
version: "3.9"

networks:
  dap_network:
    driver: bridge

services:
  leader_storage:
    networks:
      - dap_network
    ports:
      - "4000"
    extends:
      file: ../daphne-worker-test/docker-compose-storage-proxy.yaml
      service: leader_storage
  helper_storage:
    networks:
      - dap_network
    ports:
      - "4001"
    extends:
      file: ../daphne-worker-test/docker-compose-storage-proxy.yaml
      service: helper_storage
  leader:
    networks:
      - dap_network
    ports:
      - "8787"
    build:
      context: ../..
      dockerfile: crates/daphne-server/docker/example-service.Dockerfile
      target: leader
    depends_on:
      - leader_storage
    environment:
      - RUST_LOG=info
  helper:
    networks:
      - dap_network
    ports:
      - "8788"
    build:
      context: ../..
      dockerfile: crates/daphne-server/docker/example-service.Dockerfile
      target: helper
    depends_on:
      - helper_storage
    environment:
      - DAP_SERVICE__SIGNING_KEY=${HPKE_SIGNING_KEY}
      - RUST_LOG=info
  test:
    networks:
      - dap_network
    build:
      context: ../..
      dockerfile: crates/daphne-worker-test/docker/runtests.Dockerfile
    depends_on:
      - leader
      - helper
    environment:
      - E2E_TEST_HPKE_SIGNING_CERTIFICATE=${E2E_TEST_HPKE_SIGNING_CERTIFICATE}
