# Copyright (c) 2024 Cloudflare, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

name = "daphne_storage_proxy"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-21"

[build]
command = "cargo install --git https://github.com/cloudflare/workers-rs && worker-build --dev"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

# NOTE: Variables marked as SECRET need to be provisioned securely in
# production. In particular, they will not be passed as environment variables
# as they are here. See
# https://developers.cloudflare.com/workers/wrangler/commands/#secret.
[vars]
DAPHNE_SERVER_AUTH_TOKEN = "this-is-the-storage-proxy-auth-token" # SECRET
DAP_WORKER_MODE = "storage-proxy"
DAP_DEPLOYMENT = "dev"
DAP_DURABLE_HELPER_STATE_STORE_GC_AFTER_SECS = "30"
DAP_DURABLE_AGGREGATE_STORE_GC_AFTER_SECS = "30"

[durable_objects]
bindings = [
    { name = "DAP_AGGREGATE_STORE", class_name = "AggregateStore" },
    { name = "DAP_GARBAGE_COLLECTOR", class_name = "GarbageCollector" },
    { name = "DAP_HELPER_STATE_STORE", class_name = "HelperStateStore" },
]


[[kv_namespaces]]
binding = "DAP_CONFIG"
# KV bindings are in a looked up in a namespace identified by a 16-byte id number.
# This number is assigned by calling
#
#    wrangler kv:namespace create <NAME>
#
# for some unique name you specify, and it returns a unique id number to use.
# Here we should use something like "leader" for the <NAME>.
id = "<assign-one-for-the-leader>"
# A "preview id" is an id used when running in "wrangler dev" mode locally, and
# can just be made up.  We generated the number below with the following python
# code:
#
#    import secrets
#    print(secrets.token_hex(16))
#
preview_id = "24c4dc92d5cf4680e508fe18eb8f0281"

[[migrations]]
tag = "v1"
new_classes = [
    "AggregateStore",
    "GarbageCollector",
    "HelperStateStore",
]
